export type Config = {
  REACT_APP_SPOTIFY_API_CLIENT_ID: string;
  REACT_APP_SPOTIFY_API_CLIENT_SECRET: string;
  REACT_APP_SPOTIFY_LOGIN_REDIRECT_PATH: string;
  REACT_APP_SPOTIFY_ACCOUNTS_BASE_URL: string;
  REACT_APP_SPOTIFY_API_BASE_URL: string;
};

